In [39]:
import os
import pandas as pd
from sqlalchemy import create_engine

In [41]:
df=pd.read_csv('/home/mariahwarren/CTA_-_Ridership_-_Daily_Boarding_Totals_20241205.csv')
df2=pd.read_csv('/home/mariahwarren/MTA_Monthly_Ridership___Traffic_Data__Beginning_January_2008.csv')

In [43]:
df

     service_date day_type     bus  rail_boardings  total_rides
0      01/01/2001        U  297192          126455       423647
1      01/02/2001        W  780827          501952      1282779
2      01/03/2001        W  824923          536432      1361355
3      01/04/2001        W  870021          550011      1420032
4      01/05/2001        W  890426          557917      1448343
...           ...      ...     ...             ...          ...
8731   09/26/2024        W  659106          474890      1133996
8732   09/27/2024        W  564419          418093       982512
8733   09/28/2024        A  384642          312755       697397
8734   09/29/2024        U  312714          246922       559636
8735   09/30/2024        W  619994          406220      1026214

[8736 rows x 5 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8736 entries, 0 to 8735
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    8736 non-null   object
 1   day_type        8736 non-null   object
 2   bus             8736 non-null   int64
 3   rail_boardings  8736 non-null   int64
 4   total_rides     8736 non-null   int64
dtypes: int64(3), object(2)
memory usage: 341.4+ KB

In [17]:
df.describe()

                bus  rail_boardings   total_rides
count  8.736000e+03    8.736000e+03  8.736000e+03
mean   7.147875e+05    5.142161e+05  1.229004e+06
std    2.703978e+05    2.085122e+05  4.655144e+05
min    8.078300e+04    2.354400e+04  1.100470e+05
25%    4.639372e+05    3.279048e+05  8.030615e+05
50%    7.811000e+05    5.878205e+05  1.463178e+06
75%    9.611498e+05    6.952590e+05  1.633431e+06
max    1.211992e+06    1.146516e+06  2.049519e+06

In [19]:
df.describe(include=object)

       service_date day_type
count          8736     8736
unique         8674        3
top      07/02/2014        W
freq              2     6101

In [45]:
df['service_date']=pd.to_datetime(df['service_date'])
df.set_index('service_date',inplace=True)
df[['bus','rail_boardings','total_rides']]=df[['bus','rail_boardings','total_rides']].resample('ME').sum()
df

             day_type         bus  rail_boardings  total_rides
service_date
2001-01-01          U         NaN             NaN          NaN
2001-01-02          W         NaN             NaN          NaN
2001-01-03          W         NaN             NaN          NaN
2001-01-04          W         NaN             NaN          NaN
2001-01-05          W         NaN             NaN          NaN
...               ...         ...             ...          ...
2024-09-26          W         NaN             NaN          NaN
2024-09-27          W         NaN             NaN          NaN
2024-09-28          A         NaN             NaN          NaN
2024-09-29          U         NaN             NaN          NaN
2024-09-30          W  16161092.0      11665977.0   27827069.0

[8736 rows x 4 columns]

In [47]:
df.reset_index(inplace=True)
df

     service_date day_type         bus  rail_boardings  total_rides
0      2001-01-01        U         NaN             NaN          NaN
1      2001-01-02        W         NaN             NaN          NaN
2      2001-01-03        W         NaN             NaN          NaN
3      2001-01-04        W         NaN             NaN          NaN
4      2001-01-05        W         NaN             NaN          NaN
...           ...      ...         ...             ...          ...
8731   2024-09-26        W         NaN             NaN          NaN
8732   2024-09-27        W         NaN             NaN          NaN
8733   2024-09-28        A         NaN             NaN          NaN
8734   2024-09-29        U         NaN             NaN          NaN
8735   2024-09-30        W  16161092.0      11665977.0   27827069.0

[8736 rows x 5 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8736 entries, 0 to 8735
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    8736 non-null   datetime64[ns]
 1   day_type        8736 non-null   object
 2   bus             287 non-null    float64
 3   rail_boardings  287 non-null    float64
 4   total_rides     287 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 341.4+ KB

In [49]:
df.dropna()

     service_date day_type         bus  rail_boardings  total_rides
30     2001-01-31        W  25022908.0      14712334.0   39735242.0
58     2001-02-28        W  23768892.0      13669269.0   37438161.0
89     2001-03-31        A  26827165.0      15463578.0   42290743.0
119    2001-04-30        W  25053791.0      14713336.0   39767127.0
150    2001-05-31        W  26743744.0      15743730.0   42487474.0
...           ...      ...         ...             ...          ...
8613   2024-05-31        W  16367601.0      11330441.0   27698042.0
8643   2024-06-30        U  14742769.0      10928671.0   25671440.0
8674   2024-07-31        W  15306884.0      11279758.0   26586642.0
8705   2024-08-31        A  15534600.0      11744693.0   27279293.0
8735   2024-09-30        W  16161092.0      11665977.0   27827069.0

[287 rows x 5 columns]

In [51]:
df.dropna(inplace=True)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287 entries, 30 to 8735
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    287 non-null    datetime64[ns]
 1   day_type        287 non-null    object
 2   bus             287 non-null    float64
 3   rail_boardings  287 non-null    float64
 4   total_rides     287 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 13.5+ KB

In [55]:
df

     service_date day_type         bus  rail_boardings  total_rides
30     2001-01-31        W  25022908.0      14712334.0   39735242.0
58     2001-02-28        W  23768892.0      13669269.0   37438161.0
89     2001-03-31        A  26827165.0      15463578.0   42290743.0
119    2001-04-30        W  25053791.0      14713336.0   39767127.0
150    2001-05-31        W  26743744.0      15743730.0   42487474.0
...           ...      ...         ...             ...          ...
8613   2024-05-31        W  16367601.0      11330441.0   27698042.0
8643   2024-06-30        U  14742769.0      10928671.0   25671440.0
8674   2024-07-31        W  15306884.0      11279758.0   26586642.0
8705   2024-08-31        A  15534600.0      11744693.0   27279293.0
8735   2024-09-30        W  16161092.0      11665977.0   27827069.0

[287 rows x 5 columns]

In [57]:
df.rename(columns={'service_date': 'Month','rail_boardings':'metro'},inplace=True)
df.drop(['day_type','total_rides'],axis=1,inplace=True)
df['city']='Chicago'
df

          Month         bus       metro     city
30   2001-01-31  25022908.0  14712334.0  Chicago
58   2001-02-28  23768892.0  13669269.0  Chicago
89   2001-03-31  26827165.0  15463578.0  Chicago
119  2001-04-30  25053791.0  14713336.0  Chicago
150  2001-05-31  26743744.0  15743730.0  Chicago
...         ...         ...         ...      ...
8613 2024-05-31  16367601.0  11330441.0  Chicago
8643 2024-06-30  14742769.0  10928671.0  Chicago
8674 2024-07-31  15306884.0  11279758.0  Chicago
8705 2024-08-31  15534600.0  11744693.0  Chicago
8735 2024-09-30  16161092.0  11665977.0  Chicago

[287 rows x 4 columns]

In [59]:
df=df.melt(id_vars=['Month','city'],value_vars=['bus','metro'],var_name='transportation_type',value_name='ridership_count')
df

         Month     city transportation_type  ridership_count
0   2001-01-31  Chicago                 bus       25022908.0
1   2001-02-28  Chicago                 bus       23768892.0
2   2001-03-31  Chicago                 bus       26827165.0
3   2001-04-30  Chicago                 bus       25053791.0
4   2001-05-31  Chicago                 bus       26743744.0
..         ...      ...                 ...              ...
569 2024-05-31  Chicago               metro       11330441.0
570 2024-06-30  Chicago               metro       10928671.0
571 2024-07-31  Chicago               metro       11279758.0
572 2024-08-31  Chicago               metro       11744693.0
573 2024-09-30  Chicago               metro       11665977.0

[574 rows x 4 columns]

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month                574 non-null    datetime64[ns]
 1   city                 574 non-null    object
 2   transportation_type  574 non-null    object
 3   ridership_count      574 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 18.1+ KB

In [63]:
df.describe(exclude=['datetime64','object'])

       ridership_count
count     5.740000e+02
mean      1.902328e+07
std       6.699584e+06
min       2.235078e+06
25%       1.519061e+07
50%       1.919992e+07
75%       2.393611e+07
max       5.536217e+07

In [65]:
df.describe(include=object)

           city transportation_type
count       574                 574
unique        1                   2
top     Chicago                 bus
freq        574                 287

In [71]:
df2

          Month    Agency    Ridership
0    2008-01-01       MNR    6453734.0
1    2008-02-01       MNR    6144377.0
2    2008-03-01       MNR    6602280.0
3    2008-04-01       B&T   24900328.0
4    2008-04-01       MNR    6787480.0
..          ...       ...          ...
848  2024-10-01  NYCT Bus   31811369.0
849  2024-10-01       SIR          0.0
850  2024-10-01       SIR     230381.0
851  2024-10-01    Subway          0.0
852  2024-10-01    Subway  113310626.0

[853 rows x 3 columns]

In [73]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Month      853 non-null    object
 1   Agency     853 non-null    object
 2   Ridership  853 non-null    float64
dtypes: float64(1), object(2)
memory usage: 20.1+ KB

In [75]:
df2.describe()

          Ridership
count  8.530000e+02
mean   2.071912e+07
std    2.961551e+07
min    0.000000e+00
25%    4.170715e+06
50%    7.230193e+06
75%    2.621875e+07
max    1.553157e+08

In [77]:
df2.describe(include=object)

             Month Agency
count          853    853
unique         202     10
top     2024-10-01    MNR
freq            16    203

In [79]:
df2['Month']=pd.to_datetime(df2['Month'])
df2

         Month    Agency    Ridership
0   2008-01-01       MNR    6453734.0
1   2008-02-01       MNR    6144377.0
2   2008-03-01       MNR    6602280.0
3   2008-04-01       B&T   24900328.0
4   2008-04-01       MNR    6787480.0
..         ...       ...          ...
848 2024-10-01  NYCT Bus   31811369.0
849 2024-10-01       SIR          0.0
850 2024-10-01       SIR     230381.0
851 2024-10-01    Subway          0.0
852 2024-10-01    Subway  113310626.0

[853 rows x 3 columns]

In [81]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Month      853 non-null    datetime64[ns]
 1   Agency     853 non-null    object
 2   Ridership  853 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 20.1+ KB

In [83]:
# If Agency has "Bus" in name, it's a bus. Everything else is metro
df2['Agency'].unique()

array(['MNR', 'B&T', 'Bus', 'Subway', 'AAR', 'BT', 'LIRR', 'MTA Bus',
       'NYCT Bus', 'SIR'], dtype=object)

In [85]:
df2['transportation_type']=None
df2

         Month    Agency    Ridership transportation_type
0   2008-01-01       MNR    6453734.0                None
1   2008-02-01       MNR    6144377.0                None
2   2008-03-01       MNR    6602280.0                None
3   2008-04-01       B&T   24900328.0                None
4   2008-04-01       MNR    6787480.0                None
..         ...       ...          ...                 ...
848 2024-10-01  NYCT Bus   31811369.0                None
849 2024-10-01       SIR          0.0                None
850 2024-10-01       SIR     230381.0                None
851 2024-10-01    Subway          0.0                None
852 2024-10-01    Subway  113310626.0                None

[853 rows x 4 columns]

In [87]:
df2.loc[df2['Agency']=='Bus','transportation_type']='bus'
df2.loc[df2['Agency']=='MTA Bus','transportation_type']='bus'
df2.loc[df2['Agency']=='NYCT Bus','transportation_type']='bus'
df2.loc[df2['Agency']=='MNR','transportation_type']='metro'
df2.loc[df2['Agency']=='B&T','transportation_type']='metro'
df2.loc[df2['Agency']=='Subway','transportation_type']='metro'
df2.loc[df2['Agency']=='AAR','transportation_type']='metro'
df2.loc[df2['Agency']=='BT','transportation_type']='metro'
df2.loc[df2['Agency']=='LIRR','transportation_type']='metro'
df2.loc[df2['Agency']=='SIR','transportation_type']='metro'

In [89]:
df2

         Month    Agency    Ridership transportation_type
0   2008-01-01       MNR    6453734.0               metro
1   2008-02-01       MNR    6144377.0               metro
2   2008-03-01       MNR    6602280.0               metro
3   2008-04-01       B&T   24900328.0               metro
4   2008-04-01       MNR    6787480.0               metro
..         ...       ...          ...                 ...
848 2024-10-01  NYCT Bus   31811369.0                 bus
849 2024-10-01       SIR          0.0               metro
850 2024-10-01       SIR     230381.0               metro
851 2024-10-01    Subway          0.0               metro
852 2024-10-01    Subway  113310626.0               metro

[853 rows x 4 columns]

In [91]:
df2['transportation_type'].unique()

array(['metro', 'bus'], dtype=object)

In [93]:
df2.drop('Agency',axis=1,inplace=True)
df2.rename(columns={'Ridership': 'ridership_count'},inplace=True)
df2['city']='New York City'
df2

         Month  ridership_count transportation_type           city
0   2008-01-01        6453734.0               metro  New York City
1   2008-02-01        6144377.0               metro  New York City
2   2008-03-01        6602280.0               metro  New York City
3   2008-04-01       24900328.0               metro  New York City
4   2008-04-01        6787480.0               metro  New York City
..         ...              ...                 ...            ...
848 2024-10-01       31811369.0                 bus  New York City
849 2024-10-01              0.0               metro  New York City
850 2024-10-01         230381.0               metro  New York City
851 2024-10-01              0.0               metro  New York City
852 2024-10-01      113310626.0               metro  New York City

[853 rows x 4 columns]

In [95]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month                853 non-null    datetime64[ns]
 1   ridership_count      853 non-null    float64
 2   transportation_type  853 non-null    object
 3   city                 853 non-null    object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 26.8+ KB

In [97]:
df2.describe(exclude=['datetime64','object'])

       ridership_count
count     8.530000e+02
mean      2.071912e+07
std       2.961551e+07
min       0.000000e+00
25%       4.170715e+06
50%       7.230193e+06
75%       2.621875e+07
max       1.553157e+08

In [99]:
df2.describe(include=object)

       transportation_type           city
count                  853            853
unique                   2              1
top                  metro  New York City
freq                   699            853

In [101]:
combined_df=pd.concat([df,df2],ignore_index=True)

In [103]:
combined_df

          Month           city transportation_type  ridership_count
0    2001-01-31        Chicago                 bus       25022908.0
1    2001-02-28        Chicago                 bus       23768892.0
2    2001-03-31        Chicago                 bus       26827165.0
3    2001-04-30        Chicago                 bus       25053791.0
4    2001-05-31        Chicago                 bus       26743744.0
...         ...            ...                 ...              ...
1422 2024-10-01  New York City                 bus       31811369.0
1423 2024-10-01  New York City               metro              0.0
1424 2024-10-01  New York City               metro         230381.0
1425 2024-10-01  New York City               metro              0.0
1426 2024-10-01  New York City               metro      113310626.0

[1427 rows x 4 columns]

In [107]:
combined_df.rename(columns={'Month': 'month'},inplace=True)

In [109]:
combined_df

          month           city transportation_type  ridership_count
0    2001-01-31        Chicago                 bus       25022908.0
1    2001-02-28        Chicago                 bus       23768892.0
2    2001-03-31        Chicago                 bus       26827165.0
3    2001-04-30        Chicago                 bus       25053791.0
4    2001-05-31        Chicago                 bus       26743744.0
...         ...            ...                 ...              ...
1422 2024-10-01  New York City                 bus       31811369.0
1423 2024-10-01  New York City               metro              0.0
1424 2024-10-01  New York City               metro         230381.0
1425 2024-10-01  New York City               metro              0.0
1426 2024-10-01  New York City               metro      113310626.0

[1427 rows x 4 columns]

In [111]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1427 entries, 0 to 1426
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                1427 non-null   datetime64[ns]
 1   city                 1427 non-null   object
 2   transportation_type  1427 non-null   object
 3   ridership_count      1427 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 44.7+ KB

In [113]:
combined_df.describe(exclude=['datetime64','object'])

       ridership_count
count     1.427000e+03
mean      2.003698e+07
std       2.329722e+07
min       0.000000e+00
25%       6.767150e+06
50%       1.701972e+07
75%       2.506442e+07
max       1.553157e+08

In [117]:
combined_df.describe(include=object)

                 city transportation_type
count            1427                1427
unique              2                   2
top     New York City               metro
freq              853                 986

In [119]:
# Converting DataFrame to CSV
combined_df.to_csv('PublicTransitDatabase.csv')

Unfortunately, I am unable to use SQLAlchemy to connect the dataframe(s) to my postgres database in PGAdmin in order to create a SQL table. I can create the engine, but I can't make the connection. Every time I attempt to do this, my kernel in Jupyter Notebook dies and I receive this message "The kernel for JupyterNotebookProjects/PublicTransitDatabase.ipynb appears to have died. It will restart automatically." I recently updated Juypter Notebook and SQLAlchemy to their current versions and I'm still receiving the same response. So, I converted the dataframe into a CSV and imported the CSV into PGAdmin4 to complete the SQL part of the assignment. Refer to PublicTransitDatabase.sql for the SQL part of the assignment.